### PR TITLE
Added function to manipulate array

### PR DESCRIPTION
**Pull request by tnemotox**
I'm not good at English, so tests and PR sentences may not be good, but I want you to forgive me.

I added a function to manipulate the array of stores that used after importing into mutation like "updateField".
I want you to see how to use added test.

### CODE REVIEW

**Comment by tnemotox** [comment]
There was a test mistake, so I pushed it again. Should I rebase and give out PR again?

**Comment by maoberlehner** [comment]
Hey! Thanks for contributing. Yes please rebase :)

**Comment by maoberlehner** [comment]
I've just seen that this adds "a lot" of new code (considering that the current codebase is very minimal). Can you give me an example in which situations this new methods are useful? Thanks!

**Comment by tnemotox** [comment]
The way to substitute mapField is very smart! It was overlooking!

I thought that a new function is necessary to manipulate the array of state, but that is enough. As you say, my code is "a lot".

I will close this PR. Thanks!

**Pull request closed without merging**
